;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.AdditionalRushAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Death",DevComment="")
+GameplayTagList=(Tag="Ability.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.RushAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Stun",DevComment="")
+GameplayTagList=(Tag="Ability.TantacleBoss",DevComment="")
+GameplayTagList=(Tag="Ability.TantacleBoss.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.TantacleBoss.Attack.Left",DevComment="")
+GameplayTagList=(Tag="Ability.TantacleBoss.Attack.Right",DevComment="")
+GameplayTagList=(Tag="Ability.TantacleBoss.StabAttack",DevComment="")
+GameplayTagList=(Tag="Ability.TantacleBoss.StabReady",DevComment="")
+GameplayTagList=(Tag="BossMonster.Phase.Die",DevComment="")
+GameplayTagList=(Tag="BossMonster.Phase.Phase1",DevComment="")
+GameplayTagList=(Tag="BossMonster.Phase.Phase2",DevComment="")
+GameplayTagList=(Tag="BossMonster.Phase.Phase3",DevComment="")
+GameplayTagList=(Tag="Combat.HitPart.Body",DevComment="")
+GameplayTagList=(Tag="Combat.HitPart.Head",DevComment="")
+GameplayTagList=(Tag="Combat.HitPart.Leg.Left",DevComment="")
+GameplayTagList=(Tag="Combat.HitPart.Leg.Right",DevComment="")
+GameplayTagList=(Tag="Combat.TakeDamage.NonGas",DevComment="")
+GameplayTagList=(Tag="Interaction.Object.Door",DevComment="")
+GameplayTagList=(Tag="Interaction.Object.Window",DevComment="")
+GameplayTagList=(Tag="State.Awake",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.RushAttack",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.Tentacle.Attack",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.Tentacle.Stab",DevComment="")
+GameplayTagList=(Tag="State.Rushing",DevComment="")
+GameplayTagList=(Tag="State.Sleep",DevComment="")
+GameplayTagList=(Tag="State.Stun",DevComment="")

